version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: on-failure
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
